"""ONXBUILD generation with machine-readable metadata and ordinary shell phases."""
import hashlib
import json
import re
import shlex
from pathlib import Path

NAME = r'[a-zA-Z0-9][a-zA-Z0-9+_.-]*'
VERSION = r'[0-9]+(?:\.[0-9]+)*[a-z]?(?:_(?:alpha|beta|pre|rc|cvs|svn|git|hg|p)[0-9]*)*'
PREFIX = "# onx-meta: "

def validate(meta):
    if meta.get("format") != 1:
        raise ValueError("unsupported ONXBUILD format")
    for key in ("name",):
        if not re.fullmatch(NAME, meta.get(key, "")):
            raise ValueError("invalid " + key)
    if not re.fullmatch(VERSION, meta.get("version", "")):
        raise ValueError("unsupported package version")
    if not isinstance(meta.get("release"), int) or meta["release"] < 0:
        raise ValueError("invalid release")
    if meta.get("arch") not in ("x86_64", "aarch64", "noarch"):
        raise ValueError("unsupported architecture")
    for key in ("description", "license", "homepage"):
        if not isinstance(meta.get(key), str) or '\n' in meta[key]:
            raise ValueError("invalid " + key)
    for key in ("builddeps", "targetdeps", "checkdeps", "rundeps"):
        if not isinstance(meta.get(key), list):
            raise ValueError("missing dependency list: " + key)
        for dependency in meta[key]:
            if not re.fullmatch(NAME + r'(?:(?:>=|<=|=|>|<)' + VERSION + r'(?:-r[0-9]+)?)?', dependency):
                raise ValueError("invalid dependency: " + dependency)
    if meta.get("build_system") not in ("configure", "autotools", "cmake", "meson"):
        raise ValueError("unsupported build system")
    for option in meta.get("configure_args", []):
        if not isinstance(option, str) or '\n' in option:
            raise ValueError("invalid configure argument")
    for key in ("configure_command", "build_command", "check_command", "package_command"):
        if key in meta and (not isinstance(meta[key], str) or '\n' in meta[key] or not meta[key].strip()):
            raise ValueError("invalid " + key)
    src = meta["source"]
    if not src["url"].startswith("https://"):
        raise ValueError("source must use HTTPS")
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9._+-]*', src["filename"]):
        raise ValueError("invalid source filename")
    if not re.fullmatch(r'[a-f0-9]{128}', src["sha512"]):
        raise ValueError("missing pinned source SHA512")
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9._+-]*', meta["source_dir"]):
        raise ValueError("invalid source directory")
    if not isinstance(meta.get("flat_source", False), bool):
        raise ValueError("invalid flat source flag")
    if meta.get("status") not in ("reviewed", "draft"):
        raise ValueError("missing review status")

def render(meta):
    validate(meta)
    q = shlex.quote
    output = ["# ONXBUILD format 1 - generated by onx; upstream build adapter.",
              PREFIX + json.dumps(meta, sort_keys=True, separators=(',', ':'))]
    for key, val in (("pkgname", meta["name"]), ("pkgver", meta["version"]),
                     ("pkgrel", str(meta["release"])), ("pkgdesc", meta["description"]),
                     ("url", meta["homepage"]), ("license", meta["license"]), ("arch", meta["arch"]),
                     ("source", meta["source"]["url"]),
                     ("sha512sums", meta["source"]["sha512"] + "  " + meta["source"]["filename"])):
        output.append(key + "=" + q(val))
    for key in ("builddeps", "targetdeps", "checkdeps", "rundeps"):
        output.append(key + "=" + q(" ".join(meta[key])))
    args = " ".join(q(x) for x in meta.get("configure_args", []))
    system = meta["build_system"]
    if system in ("configure", "autotools"):
        configure = './configure --prefix=/usr ' + args
        build = 'make -j"$jobs"'
        check = 'make check'
        package = 'make DESTDIR="$pkgdir" install'
    elif system == "cmake":
        configure = 'cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=/usr ' + args
        build = 'cmake --build _build --parallel "$jobs"'
        check = 'ctest --test-dir _build --output-on-failure'
        package = 'DESTDIR="$pkgdir" cmake --install _build'
    else:
        configure = 'meson setup _build --prefix=/usr ' + args
        build = 'meson compile -C _build -j "$jobs"'
        check = 'meson test -C _build --print-errorlogs'
        package = 'DESTDIR="$pkgdir" meson install -C _build'
    configure = meta.get("configure_command", configure)
    build = meta.get("build_command", build)
    check = meta.get("check_command", check)
    package = meta.get("package_command", package)
    for function, body in (("configure", configure), ("build", build), ("check", check), ("package", package)):
        output.extend(("", function + "() {", "    " + body.strip(), "}"))
    return "\n".join(output) + "\n"

def read(path):
    path = Path(path)
    content = path.read_text()
    lines = [line[len(PREFIX):] for line in content.splitlines() if line.startswith(PREFIX)]
    if len(lines) != 1:
        raise ValueError("ONXBUILD must contain exactly one onx-meta record")
    meta = json.loads(lines[0])
    validate(meta)
    # v0.1 supports generated recipes only; metadata cannot disagree with executed phases.
    if content != render(meta):
        raise ValueError("ONXBUILD differs from its declared adapter; edit policy and regenerate")
    return meta

def write(directory, meta, report):
    directory = Path(directory)
    if directory.exists():
        raise ValueError("refusing to overwrite existing recipe: " + str(directory))
    directory.mkdir(parents=True)
    (directory / "ONXBUILD").write_text(render(meta))
    (directory / "import-report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
